import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { AnimatedGradient } from "@/components/ui/animated-gradient";
import { FloatingCars } from "@/components/ui/floating-cars";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AnimatedGradient />
        <FloatingCars />
        {children}
      </body>
    </html>
  );
}
